### PR TITLE
Add `assert_err_eq!` macro

### PR DESCRIPTION
**Pull request by mattwilkinsonn**
This text is copied from [the original PR](https://github.com/svartalf/rust-claim/pull/8). Thanks to @Anders429!

Introduces an `assert_err_eq!` macro, which asserts that a `Result` value is an `Err` and that its contained value is equal to the provided value. Also defines a `debug_assert_err_eq!` macro.

This is very similar to the `assert_ok_eq!` macro, and I think this nicely fills out the macros provided by this library. Similarly, the `debug_assert_err_eq!` macro is very similar to the `debug_assert_ok_eq!` macro.

### CODE REVIEW

**Comment by Anders429** [comment]
Thanks a ton! I use this macro all the time in several projects, so it will be nice to have it merged into this library and published, instead of me using my own fork.

**Comment by mattwilkinsonn** [comment]
@Anders429 - could you change all instances of `claim` to `claims` in your doctests? You can open a new PR from a new branch if that works better.

**Comment by Anders429** [comment]
Absolutely, I'll see if I can fix it when I get a moment today. Thanks :)

**Comment by mattwilkinsonn** [comment]
Gonna merge this into a branch here and change those `claim` to `claims` to make it easier.

**Comment by Anders429** [comment]
@mattwilkinsonn thanks, I didn't get a chance to do anything with it tonight, but that is definitely the easiest way. I saw you published it on crates.io as well, I'll give it a try :)

**Pull request merged**
